import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-news-area',
  templateUrl: './news-area.component.html',
  styleUrls: ['./news-area.component.css']
})
export class NewsAreaComponent implements OnInit {


  constructor() { }

  ngOnInit(): void {
  }

  newsData=[{
    photo:"assets/img/trending/trending_top.jpg",
    heading1:"Here come the moms in space",
    para1:"Moms are like…buttons? Moms are like glue. Moms are like pizza crusts. Moms are the ones who make sure things happen—from birth to school lunch.",
    para2:"Moms are like…buttons? Moms are like glue. Moms are like pizza crusts. Moms are the ones who make sure things happen—from birth to school lunch.",
    para3:"My hero when I was a kid was my mom. Same for everyone I knew. Moms are untouchable. They’re elegant, smart, beautiful, kind…everything we want to be. At 29 years old, my favorite compliment is being told that I look like my mom. Seeing myself in her image, like this daughter up top, makes me so proud of how far I’ve come, and so thankful for where I come from. the refractor telescope uses a convex lens to focus the light on the eyepiece. The reflector telescope has a concave lens which means it bends in. It uses mirrors to focus the image that you eventually see. Collimation is a term for how well tuned the telescope is to give you a good clear image of what you are looking at. You want your telescope to have good collimation so you are not getting a false image of the celestial body. Aperture is a fancy word for how big the lens of your telescope is. But it’s an important word because the aperture of the lens is the key to how powerful your telescope is. Magnification has nothing to do with it, its all in the aperture. Focuser is the housing that keeps the eyepiece of the telescope, or what you will look through, in place. The focuser has to be stable and in good repair for you to have an image you can rely on. Mount and Wedge. Both of these terms refer to the tripod your telescope sits on. The mount is the actual tripod and the wedge is the device that lets you attach the telescope to the mount. Moms are like…buttons? Moms are like glue. Moms are like pizza crusts. Moms are the ones who make sure things happen—from birth to school lunch.",
    heading2:"Unordered list style?",
    para4:"The refractor telescope uses a convex lens to focus the light on the eyepiece. The reflector telescope has a concave lens which means it bends in. It uses mirrors to focus the image that you eventually see.",
    para6:"Collimation is a term for how well tuned the telescope is to give you a good clear image of what you are looking at. You want your telescope to have good collimation so you are not getting a false image of the celestial body.",
    para7:"My hero when I was a kid was my mom. Same for everyone I knew. Moms are untouchable. They’re elegant, smart, beautiful, kind…everything we want to be. At 29 years old, my favorite compliment is being told that I look like my mom. Seeing myself in her image, like this daughter up top, makes me so proud of how far I’ve come, and so thankful for where I come from. the refractor telescope uses a convex lens to focus the light on the eyepiece. The reflector telescope has a concave lens which means it bends in. It uses mirrors to focus the image that you eventually see. Collimation is a term fo Moms are like…buttons? Moms are like glue. Moms are like pizza crusts. Moms are the ones who make sure things happen—from birth to school lunch.",
    para8:"Mount and Wedge. Both of these terms refer to the tripod your telescope sits on. The mount is the actual tripod and the wedge is the device that lets you attach the telescope to the mount. Moms are like…buttons? Moms are like glue. Moms are like pizza crusts. Moms are the ones who make sure things happen—from birth to school lunch."
  },
  {
    photo:"assets/img/trending/right1.jpg",
    heading1:"Use you camera right in concerts",
    para1:"Always shoot in landscape mode. Yes, in a crowded concert it may be easier to shoot in portrait, but once you are done you will realise that video you shot has ungainly black bars on the YouTube and Facebook. Frankly, this will not please anyone. Hence, always shoot in landscape.",
    para2:"Use the default camera app that comes preloaded on your phone. Yes, third party apps may add some extra features, but largely they do not utilise the hardware that your phone packs in. This is unless you are using some specialised app that has some special features.",
    para3:"The stock camera app will enable you to access camera features with greater ease. So you can decide to shoot in 4K if your phone supports it. On a third party app, this function may not be supported. Keep your hands steady, particularly the wrist and slowly move sideways if you want to pan across to get a wider field of view. The faster you move, the shakier your video gets. Apps like Vyclone can go a long way in adding a level of professional dimension to your videos. It's an interesting app because if you are in a big group and everyone is shooting the same concert, the app is able to take different camera angles from different users and perfectly sync the audio like a professional multi camera setup.Don't zoom in. Digital zoom will induce even more camera shake, so it will be better if you could move physically closer to the action.Audio is crucial to the quality of a great bootlegged video. Now, if your phone is equipped with poor microphones then the audio is bound to be bad. However, often while taking videos in a concert situation, you may accidentally cover the microphone with your fingers. Be mindful of that and avoid covering the microphones of your device.Smartphones allow you to shoot video at a concert, but are you doing them the right way?",
    heading2:"Top 20 songs trending right now",
    para4:"This song, MUNA, “Silk Chiffon” feat. Phoebe Bridgers. Saddest Factory signees MUNA recruit their label boss Phoebe Bridgers to talk about the weightless feel of true love on “Silk Chiffon.” Mixing breezy acoustic guitars and big ‘80s pop choruses is a big part of the MUNA DNA and they deliver in droves here, as does Bridgers whose lyrics (“I’m high and I’m feeling anxious, Inside of the CVS”) remain deliciously on brand.",
    para5:"This Another song, Big Thief, “Certainty”.There’s always been a rustic quality to the best Big Thief songs, as if they’ve been whittled out of wood and discovered by the fireplace of an old lodge. “Certainty” is no different, playing into that image with gnarly lyrics about crooked crows “gnawing on dawn” and an undeniable campfire quality to the instrumentation. These offset a tender love song nicely and, alongside recent releases “Little Things” and “Sparrow,” suggest another great Big Thief album is in the pipeline.",
    para6:"SeeYouSpaceCowboy Misinterpreting Constellations, There’s an early 2000s scene quality to “Misinterpreting Constellations” that will be nostalgic for some and positively archaic for others but San Diego hardcore band SeeYouSpaceCowboy delivers it all with the necessary passion and commitment. Plus, hand claps make every song 50% better. That’s just science.",
    para7:"SPICE, “A Better Treatment”, SPICE are a new band from Ceremony’s Ross Farrar. They debuted in 2020 with a self-titled album and returned this month with “A Better Treatment,” their best song so far. Pain stalks all five minutes of the brooding and melodic song, from Farrar’s lyrics about how he “thought loving someone would cure my self-hatred” to the melancholy violins that sit atop dissonant guitars. That said, the song never feels defeated. If anything, it’s the hope that makes this one so special. and don't forget Parquet Courts, “Black Widow Spider”, Hatchie, “This Enchanted”, Big ‘90s energy from Hatchie on “This Enchanted,” her first single since signing to Secretly Canadian. Heartbreak, lies, and broken promises all play out on a song that disguises its tenderness with confident hooks and walls of distorted guitars.Anyone dreaming of escape may find solace in Amyl and The Sniffers’ Amy Taylor barking “Take me to the beach, take me to the country” over buzzsaw guitars. A cure for the landlocked blues aside, “Hertz” is also a taste of The Sniffers’ excellent new album Comfort To Me that dropped this month. The album is bratty and relentless and you’re going to want to check it out.",
    para8:"Snail Mail, “Valentine”, Lindsay Jordan is back with new Snail Mail music and marks her return by examining that awkward moment when an ex moves on a bit quicker than you do. “Why do you want to erase me?” she asks during the track’s exultant chorus. With a new album of the same name dropping November 5, Snail Mail will be hard to forget these next few months.Andy Shauf, “Spanish on the Beach”, Andy Shauf makes small, folksy songs with narratives that unfurl like a micro-budget indie movie. Sure, the stakes are low, but you’re fully invested from the off. He dropped a surprise album, Wilds, this month and “Spanish on the Beach” taps into Shauf’s neat storytelling ability, introducing a holiday romance that feels monumental and flyaway at the same time."
  },
  {
    photo:"assets/img/trending/right2.jpg",
    heading1:"Beaches and nature",
    para1:"A beach is a landform alongside a body of water which consists of loose particles. The particles composing a beach are typically made from rock, such as sand, gravel, shingle, pebbles, etc., or biological sources, such as mollusc shells or coralline algae.",
    para2:"Sediments settle in different densities and structures, depending on the local wave action and weather, creating different textures, colors and gradients or layers of material.",
    para3:"Though some beaches form on freshwater locations, most beaches are in coastal areas where wave or current action deposits and reworks sediments. Erosion and changing of beach geologies happens through natural processes, like wave action and extreme weather events. Where wind conditions are correct, beaches can be backed by coastal dunes which offer protection and regeneration for the beach. However, these natural forces have become more extreme due to climate change, permanently altering beaches at very rapid rates. Some estimates describe as much as 50 percent of the earth's sandy beaches disappearing by 2100 due to climate-change driven sea level rise",
    heading2:"Formation",
    para4:"Beaches are the result of wave action by which waves or currents move sand or other loose sediments of which the beach is made as these particles are held in suspension. Alternatively, sand may be moved by saltation (a bouncing movement of large particles).",
    para5:"Beach materials come from erosion of rocks offshore, as well as from headland erosion and slumping producing deposits of scree. A coral reef offshore is a significant source of sand particles. Some species of fish that feed on algae attached to coral outcrops and rocks can create substantial quantities of sand particles over their lifetime as they nibble during feeding,",
    para6:"The composition of the beach depends upon the nature and quantity of sediments upstream of the beach, and the speed of flow and turbidity of water and wind. Sediments are moved by moving water and wind according to their particle size and state of compaction. Particles tend to settle and compact in still water. Once compacted, they are more resistant to erosion.",
    para7:"Established vegetation (especially species with complex network root systems) will resist erosion by slowing the fluid flow at the surface layer. When affected by moving water or wind, particles that are eroded and held in suspension will increase the erosive power of the fluid that holds them by increasing the average density, viscosity, and volume of the moving fluid.Coastlines facing very energetic wind and wave systems will tend to hold only large rocks as smaller particles will be held in suspension in the turbid water column and carried to calmer areas by longshore currents and tides.",
    para8:"Coastlines that are protected from waves and winds will tend to allow finer sediments such as clay and mud to precipitate creating mud flats and mangrove forests. The shape of a beach depends on whether the waves are constructive or destructive"
  },
  {
    photo:"assets/img/trending/right3.jpg",
    heading1:"MotorCycle/Bikes",
    para1:"A motorcycle, often called a motorbike, bike, or cycle, is a two- or three-wheeled motor vehicle. Motorcycle design varies greatly to suit a range of different purposes: long-distance travel, commuting, cruising, sport (including racing), and off-road riding.",
    para2:" Motorcycling is riding a motorcycle and being involved in other related social activity such as joining a motorcycle club and attending motorcycle rallies.",
    para3:"The 1885 Daimler Reitwagen made by Gottlieb Daimler and Wilhelm Maybach in Germany was the first internal combustion, petroleum-fueled motorcycle. In 1894, Hildebrand & Wolfmüller became the first series production motorcycle.In 2014, the three top motorcycle producers globally by volume were Honda (28%), Yamaha (17%) (both from Japan), and Hero MotoCorp (India).[6] In developing countries, motorcycles are considered utilitarian due to lower prices and greater fuel economy. Of all the motorcycles in the world, 58% are in the Asia-Pacific and Southern and Eastern Asia regions, excluding car-centric Japan.",
    heading2:"History of Bikes",
    para4:"The first internal combustion, petroleum fueled motorcycle was the Daimler Reitwagen. It was designed and built by the German inventors Gottlieb Daimler and Wilhelm Maybach in Bad Cannstatt, Germany in 1885",
    para5:"This vehicle was unlike either the safety bicycles or the boneshaker bicycles of the era in that it had zero degrees of steering axis angle and no fork offset, and thus did not use the principles of bicycle and motorcycle dynamics developed nearly 70 years earlier.",
    para6:"The inventors called their invention the Reitwagen riding car. It was designed as an expedient testbed for their new engine, rather than a true prototype vehicle.Butler's Patent Velocycle.The first commercial design for a self-propelled cycle was a three-wheel design called the Butler Petrol Cycle, conceived of Edward Butler in England in 1884.[12] He exhibited his plans for the vehicle at the Stanley Cycle Show in London in 1884. The vehicle was built by the Merryweather Fire Engine company in Greenwich, in 1888.",
    para7:"The engine was liquid-cooled, with a radiator over the rear driving wheel. Speed was controlled by means of a throttle valve lever. No braking system was fitted; the vehicle was stopped by raising and lowering the rear driving wheel using a foot-operated lever; ",
    para8:"Many authorities have excluded steam powered, electric motorcycles or diesel-powered two-wheelers from the definition of a 'motorcycle', and credit the Daimler Reitwagen as the world's first motorcycle."
  },
  {
    photo:"assets/img/trending/right4.jpg",
    heading1:"Snowy Mountains",
    para1:"The Snowy Mountains, known informally as The Snowies, is an IBRA subregion in southern New South Wales, Australia, and is the tallest mountain range in mainland Australia, being part of the continent's Great Dividing Range cordillera system. ",
    para2:" It makes up the northeastern half of the Australian Alps (the other half being the Victorian Alps) and contains Australia's five tallest peaks, all of which are above 2,100 m (6,890 ft), including the tallest Mount Kosciuszko, which reaches to a height of 2,228 m (7,310 ft) above sea level. ",
    para3:"The offshore Tasmanian highlands makes up the only other major alpine region present in the whole of Australia.The Snowy Mountains experiences large natural snowfalls every winter, normally during June, July, August and early September, with the snow cover melting by late spring. It is considered to be one of the centers of the Australian ski industry during the winter months, with all four snow resorts in New South Wales being located in the region.[1] The range is host to the mountain plum-pine, a low-lying type of conifer.",
    heading2:"History and Geography",
    para4:"The mountain range is thought to have had Aboriginal occupation for 20,000 years. Large gatherings were held in the High Country during summer for collective feasting on the Bogong moth.",
    para5:"The mountain range is thought to have had Aboriginal occupation for 20,000 years. Large gatherings were held in the High Country during summer for collective feasting on the Bogong moth.",
    para6:"The area was first explored by Europeans in 1835, and in 1840, Edmund Strzelecki ascended Mount Kosciuszko and named it after the Polish patriot. High country stockmen followed who used the Snowy Mountains for grazing during the summer months. Banjo Paterson's famous poem The Man From Snowy River recalls this era. The cattle graziers have left a legacy of mountain huts scattered across the area. Today these huts are maintained by the National Parks and Wildlife Service or volunteer organisations like the Kosciuszko Huts Association.",
    para7:"In the 19th century gold was mined on the high plains near Kiandra. At its height this community had a population of about 4,000 people, and ran 14 hotels. Since the last resident left in 1974, Kiandra has become a ghost town of ruins and abandoned diggings.",
    para8:"The Kosciuszko National Park came into existence as the National Chase Snowy Mountains on 5 December 1906. In 1944 this became the Kosciuszko State Park, and then the Kosciuszko National Park in 1967."
  },
  {
    photo:"assets/img/trending/right5.jpg",
    heading1:"Skating and it's types",
    para1:"Skating involves any sports or recreational activity which consists of traveling on surfaces or on ice using skates.There are several different kinds of skating :",
    para2:"Skating involves any sports or recreational activity which consists of traveling on surfaces or on ice using skates.There are several different kinds of skating :",
    para3:"Skating involves any sports or recreational activity which consists of traveling on surfaces or on ice using skates.There are several different kinds of skating :Skating involves any sports or recreational activity which consists of traveling on surfaces or on ice using skates.There are several different kinds of skating :Skating involves any sports or recreational activity which consists of traveling on surfaces or on ice using skates.There are several different kinds of skating :Skating involves any sports or recreational activity which consists of traveling on surfaces or on ice using skates.There are several different kinds of skating :Skating involves any sports or recreational activity which consists of traveling on surfaces or on ice using skates.There are several different kinds of skating :Skating involves any sports or recreational activity which consists of traveling on surfaces or on ice using skates.There are several different kinds of skating :Skating involves any sports or recreational activity which consists of traveling on surfaces or on ice using skates.There are several different kinds of skating :Skating involves any sports or recreational activity which consists of traveling on surfaces or on ice using skates.There are several different kinds of skating :Skating involves any sports or recreational activity which consists of traveling on surfaces or on ice using skates.There are several different kinds of skating :Skating involves any sports or recreational activity which consists of traveling on surfaces or on ice using skates.There are several different kinds of skating :",
    Heading2:"Additional Information",
    para4:"Skating involves any sports or recreational activity which consists of traveling on surfaces or on ice using skates.There are several different kinds of skating :Skating involves any sports or recreational activity which consists of traveling on surfaces or on ice using skates.There are several different kinds of skating :",
    para5:"Skating involves any sports or recreational activity which consists of traveling on surfaces or on ice using skates.There are several different kinds of skating :",
    para6:"Skating involves any sports or recreational activity which consists of traveling on surfaces or on ice using skates.There are several different kinds of skating :Skating involves any sports or recreational activity which consists of traveling on surfaces or on ice using skates.There are several different kinds of skating :Skating involves any sports or recreational activity which consists of traveling on surfaces or on ice using skates.There are several different kinds of skating :Skating involves any sports or recreational activity which consists of traveling on surfaces or on ice using skates.There are several different kinds of skating :",
    para7:"Skating involves any sports or recreational activity which consists of traveling on surfaces or on ice using skates.There are several different kinds of skating :Skating involves any sports or recreational activity which consists of traveling on surfaces or on ice using skates.There are several different kinds of skating :Skating involves any sports or recreational activity which consists of traveling on surfaces or on ice using skates.There are several different kinds of skating :Skating involves any sports or recreational activity which consists of traveling on surfaces or on ice using skates.There are several different kinds of skating :",
    para8:"Skating involves any sports or recreational activity which consists of traveling on surfaces or on ice using skates.There are several different kinds of skating :"
  },
  {
    photo:"assets/img/trending/trending_bottom1.jpg",
    heading1:"Lifestyles blogs to follow",
    para1:"The Lifestyle Blog niche is one of the most competitive blogging niches around. Lifestyle bloggers are competing against digital lifestyle magazines, in a niche that is already quite saturated. So lifestyle blogs that gain a large readership are of a high standard in both design and content.",
    para2:"Online mags often have huge budgets, a print edition as well as digital, and content that is varied and expertly written, with professional photos. But lifestyle blogs have an edge in that they can supply new content every day if they so wish.",
    para3:"Lifestyle blogs are free to access whereas digital magazine editions can only be accessed through paid subscriptions.For a lifestyle blog to thrive, the authors need to provide excellent, accurate content and photos that create interest and capture the readers’ imaginations. Lifestyle bloggers have raised their standards to compete with the best of both online mags and other lifestyle blogs.But what exactly constitutes a lifestyle blog?",
    heading2:"Defining lifestyle blogs",
    para4:"A lifestyle blog is defined as digital content representing the author’s everyday life and interests. The word “lifestyle” according to the dictionary means “habits, attitudes, moral standards, which together constitute the way of life of a given person or group”.",
    para5:"As a result, lifestyle blogs can fall into many micro-niches. This allows bloggers to provide content for a specific target audience. Lifestyle bloggers often promote products, brands, and services to monetize their blogs.",
    para6:"Sometimes even these categories get split into various combinations, depending on the blogger. So you could end up with a Fashion and Travel Blog, A Natural Living Mom Blog, or even a Foodie and Photography Lifestyle blog.",
    para7:"Lifestyle blogs are not personal blogs because they focus more on users (readers). The content is created here for the reader and his expectations. What’s more, lifestyle blogs focus on the author’s benefits, not just on telling stories.",
    para8:"In personal blogs, the most important are the author’s emotions and thoughts, who expresses his opinions, writes about his experiences, feelings, reflections. In the personal blog, the author himself is the most important, not the reader.",
  },
  {
    photo:"assets/img/trending/trending_bottom2.jpg",
    heading1:"The best football club",
    para1:"This Monday morning the first team were back at work for the first time since losing their unbeaten record in La Liga at the hands of Atlético Madrid at the Wanda Metropolitano.",
    para2:"The players that started the game on Saturday did the usual post-game recovery routine, while the remainder trained as normal on the Tito Vilanova field at the Ciutat Esportiva under damp conditions due to the heavy rain that's falling on the Catalan capital at the moment.",
    para3:"Four FC Barcelona players are in the Spanish squad for the UEFA Nations League Final Four. Luis Enrique had already called up Eric Garcia, Sergio Busquets, and Gavi, the notable new addition to the squad, and on Sunday it was announced that as Brais Méndez is injured, Sergi Roberto will also be included as a replacement.",
    heading2:"Gavi, a potential record-breaker",
    para4:"Aged only 17 years and 56 days old, Barca's Gavi has been called up to the Asturian coach's squad and is potentially in line to make his debut.",
    para5:"This would make him the youngest ever player for Spain, beating the current record holder, Ángel Zubieta (17 years and 284 days old). Let's not forget that Ansu Fati was the second youngest player to make his debut when he was 17 years and 308 days old.",
    para6:"Gavi continues his meteoric rise, having already played and impressed in six first team games this season - four in La Liga and two in the Champions League - even though he is still officially a second year youth player.",
    para7:"Gavi continues his meteoric rise, having already played and impressed in six first team games this season - four in La Liga and two in the Champions League - even though he is still officially a second year youth player.Gavi continues his meteoric rise, having already played and impressed in six first team games this season - four in La Liga and two in the Champions League - even though he is still officially a second year youth player.",
    para8:"Aged only 17 years and 56 days old, Barca's Gavi has been called up to the Asturian coach's squad and is potentially in line to make his debut."
  },
  {
    photo:"assets/img/trending/trending_bottom3.jpg",
    heading1:"Top places to visit in India",
    para1:"The month of October kicks off the official tourism season in India as the weather becomes cool and pleasant across the country and remains the same till the end of March. Starting this month, tourists swarm to the best of the best travel destinations in the country with their family and friends for vacations. If you too have similar plans, then we suggest you to take a look at our list of 10 places to visit in October and to plan your vacations accordingly:",
    para2:"AGRA :- Agra, located on the banks of the Yamuna River, is home to one of the Seven Wonders of the World – Taj Mahal, which has put the city’s name on the list of every ardent traveler in the world. The beauty of this monument is far from being expressed in words; it can only be witnessed and admired. October presents the ideal weather to explore this fine piece of architecture and many such remarkable Mughal structures dotted in and around the city.",
    para3:"KOLKATA:- October is probably the most awaited month for the people of Kolkata as festivities take centre stage with ‘Durga Pujo’. There is happiness on everyone’s face and sparkle in the eyes as they get ready to welcome their revered deity – Goddess Durga. The festivities go on for a week or so and the whole city comes to life with families hopping from one spectacularly decorated Puja pandal to the other to take blessings from Maa Durga. Come to Kolkata in October to witness this grand celebration, and you will be utterly impressed! Places to visit in Kolkata: Victoria Memorial, Kalighat, Nicco Park, Alipore Zoo, Dakshineswar Temple, Kalighat Kali Temple, Indian Museum, Eco Park Princep Ghat and Belur Math.Things to do in Kolkata: Attend Durga Pujo festivities, shop till you drop at New Market, enjoy a day at the wonderful Science City and gorge on mouth-watering Bengali dishes, especially sweets",
    heading2:"Continued....",
    para4:"Rishikesh:-  If both sightseeing and adventure is on your mind, then coming to Rishikesh in October can be the best choice. The holy city of Rishikesh is home to several revered temples, ghats and the famous – Laxman Jhula and Ram Jhula. Considered as the Yoga Capital of India, Rishikesh also offers different avenues for adventure junkies – white river rafting, bunjee jumping, zip lining and camping along the shores of the gushing river Ganga.  ",
    para5:"Places to visit in Rishikesh: Laxman Jhula, Ram Jhula, Neelkanth Mahadev Temple, Neer Garh Waterfall, Triveni Ghat, Rishi Kund, Beatles Ashram and Swarg Ashram",
    para6:"Things to do in Rishikesh: Camp at Shivpuri, go for exciting white water rafting and get your adrenaline pumping with bunjee jumping and zip lining at Jumpin Heights ",
    para7:"Hampi :- A UNESCO World Heritage Site, Hampi in Karnataka – once home to the erstwhile Vijaynagar Kingdom – is famous for its ruins of monolithic structures, temples and monuments. The Hindu architectural style of these historic structures is worth witnessing, especially that of Virupaksha Temple, which is devoted to the patron deity of the kingdom. You can plan a trip to this city if you seek a bit of solitude and love exploring historical buildings.",
    para8:"Places to visit in Hampi: Vijaya Vittala Temple, Sri Virupaksha Temple, Hemakuta Hill Temple Complex, Hanuman Temple, Lakshmi Narasimha Temple, Riverside Ruins and Queen’s Bath"
  }
]
}
